/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FailedToCheckSubscriptionYouTubeErrorData
import org.openapitools.client.models.ApplicationNotFoundErrorData

class FailedToCheckSubscriptionYouTubeErrorDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FailedToCheckSubscriptionYouTubeErrorData
        //val modelInstance = FailedToCheckSubscriptionYouTubeErrorData()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `youtube`
        should("test youtube") {
            // uncomment below to test the property
            //modelInstance.youtube shouldBe ("TODO")
        }

    }
}
