/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.FailedToCheckSubscriptionTwitchErrorData
import org.openapitools.client.models.ApplicationNotFoundErrorData

class FailedToCheckSubscriptionTwitchErrorDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FailedToCheckSubscriptionTwitchErrorData
        //val modelInstance = FailedToCheckSubscriptionTwitchErrorData()

        // to test the property `broadcaster`
        should("test broadcaster") {
            // uncomment below to test the property
            //modelInstance.broadcaster shouldBe ("TODO")
        }

        // to test the property `viewer`
        should("test viewer") {
            // uncomment below to test the property
            //modelInstance.viewer shouldBe ("TODO")
        }

    }
}
