/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GuildNotAuthorizedErrorData
import org.openapitools.client.models.GuildNotAuthorizedErrorDataApplication
import org.openapitools.client.models.GuildNotAuthorizedErrorDataDiscord

class GuildNotAuthorizedErrorDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GuildNotAuthorizedErrorData
        //val modelInstance = GuildNotAuthorizedErrorData()

        // to test the property `application`
        should("test application") {
            // uncomment below to test the property
            //modelInstance.application shouldBe ("TODO")
        }

        // to test the property `discord`
        should("test discord") {
            // uncomment below to test the property
            //modelInstance.discord shouldBe ("TODO")
        }

    }
}
