/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GuildPermissionsNotFoundErrorDataDiscord

class GuildPermissionsNotFoundErrorDataDiscordTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GuildPermissionsNotFoundErrorDataDiscord
        //val modelInstance = GuildPermissionsNotFoundErrorDataDiscord()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `guildId`
        should("test guildId") {
            // uncomment below to test the property
            //modelInstance.guildId shouldBe ("TODO")
        }

    }
}
