/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GuildPermissionsNotFoundErrorData
import org.openapitools.client.models.GuildPermissionsNotFoundErrorDataDiscord

class GuildPermissionsNotFoundErrorDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GuildPermissionsNotFoundErrorData
        //val modelInstance = GuildPermissionsNotFoundErrorData()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `discord`
        should("test discord") {
            // uncomment below to test the property
            //modelInstance.discord shouldBe ("TODO")
        }

    }
}
