/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.MissingDataErrorData

class MissingDataErrorDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MissingDataErrorData
        //val modelInstance = MissingDataErrorData()

        // to test the property `missing`
        should("test missing") {
            // uncomment below to test the property
            //modelInstance.missing shouldBe ("TODO")
        }

    }
}
