/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.NoPatronsFoundErrorData
import org.openapitools.client.models.NoPatronsFoundErrorDataPatreon

class NoPatronsFoundErrorDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NoPatronsFoundErrorData
        //val modelInstance = NoPatronsFoundErrorData()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `patreon`
        should("test patreon") {
            // uncomment below to test the property
            //modelInstance.patreon shouldBe ("TODO")
        }

    }
}
