/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DiscordApi
import org.openapitools.client.models.GuildNotAuthorized
import org.openapitools.client.models.InvalidParameter
import org.openapitools.client.models.MyApplications401Response
import org.openapitools.client.models.MyApplications404Response

class DiscordApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DiscordApi
        //val apiInstance = DiscordApi()

        // to test myApplications
        should("test myApplications") {
            // uncomment below to test myApplications
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val serverId : kotlin.String = serverId_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.myApplications(fromPlatform, fromUserId, serverId, xSignature)
        }

        // to test userHasRoleInGuild
        should("test userHasRoleInGuild") {
            // uncomment below to test userHasRoleInGuild
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val serverId : kotlin.String = serverId_example // kotlin.String | 
            //val roleId : kotlin.String = roleId_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userHasRoleInGuild(fromPlatform, fromUserId, serverId, roleId, xSignature)
        }

    }
}
