/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.PatreonApi
import org.openapitools.client.models.InvalidParameter
import org.openapitools.client.models.MyApplications401Response
import org.openapitools.client.models.UserIsPatreonMember404Response
import org.openapitools.client.models.UserIsPatreonMemberAtTier404Response

class PatreonApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PatreonApi
        //val apiInstance = PatreonApi()

        // to test userIsPatreonMember
        should("test userIsPatreonMember") {
            // uncomment below to test userIsPatreonMember
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsPatreonMember(fromPlatform, fromUserId, xSignature)
        }

        // to test userIsPatreonMemberAtTier
        should("test userIsPatreonMemberAtTier") {
            // uncomment below to test userIsPatreonMemberAtTier
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val tierName : kotlin.String = tierName_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsPatreonMemberAtTier(fromPlatform, fromUserId, tierName, xSignature)
        }

    }
}
