/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.TwitchApi
import org.openapitools.client.models.ApplicationNotFound
import org.openapitools.client.models.FailedToCheckFollowTwitch
import org.openapitools.client.models.InvalidParameter
import org.openapitools.client.models.MyApplications401Response
import org.openapitools.client.models.UserIsSubscribedTwitch500Response

class TwitchApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TwitchApi
        //val apiInstance = TwitchApi()

        // to test userIsFollowingTwitch
        should("test userIsFollowingTwitch") {
            // uncomment below to test userIsFollowingTwitch
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsFollowingTwitch(fromPlatform, fromUserId, xSignature)
        }

        // to test userIsSubscribedAtTier
        should("test userIsSubscribedAtTier") {
            // uncomment below to test userIsSubscribedAtTier
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val tier : kotlin.String = tier_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsSubscribedAtTier(fromPlatform, fromUserId, tier, xSignature)
        }

        // to test userIsSubscribedTwitch
        should("test userIsSubscribedTwitch") {
            // uncomment below to test userIsSubscribedTwitch
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsSubscribedTwitch(fromPlatform, fromUserId, xSignature)
        }

    }
}
