/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.YouTubeApi
import org.openapitools.client.models.ApplicationNotFound
import org.openapitools.client.models.FailedToCheckSubscriptionYouTube
import org.openapitools.client.models.InvalidParameter
import org.openapitools.client.models.MyApplications401Response
import org.openapitools.client.models.UserIsMemberYouTube404Response
import org.openapitools.client.models.UserIsMemberYouTube500Response

class YouTubeApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of YouTubeApi
        //val apiInstance = YouTubeApi()

        // to test userIsMemberAtTierYouTube
        should("test userIsMemberAtTierYouTube") {
            // uncomment below to test userIsMemberAtTierYouTube
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val tier : kotlin.String = tier_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsMemberAtTierYouTube(fromPlatform, fromUserId, tier, xSignature)
        }

        // to test userIsMemberYouTube
        should("test userIsMemberYouTube") {
            // uncomment below to test userIsMemberYouTube
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsMemberYouTube(fromPlatform, fromUserId, xSignature)
        }

        // to test userIsSubscribedYouTube
        should("test userIsSubscribedYouTube") {
            // uncomment below to test userIsSubscribedYouTube
            //val fromPlatform : kotlin.String = fromPlatform_example // kotlin.String | 
            //val fromUserId : kotlin.String = fromUserId_example // kotlin.String | 
            //val xSignature : kotlin.String = xSignature_example // kotlin.String | 
            //apiInstance.userIsSubscribedYouTube(fromPlatform, fromUserId, xSignature)
        }

    }
}
