/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ApplicationNotFoundErrorData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param discord 
 */


data class GuildsNotFoundErrorData (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "discord")
    val discord: ApplicationNotFoundErrorData? = null

) {


}

