/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param guildId 
 */


data class GuildPermissionsNotFoundErrorDataDiscord (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "guild_id")
    val guildId: kotlin.String? = null

) {


}

