/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GuildNotAuthorizedErrorDataApplication
import org.openapitools.client.models.GuildNotAuthorizedErrorDataDiscord

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param application 
 * @param discord 
 */


data class GuildNotAuthorizedErrorData (

    @Json(name = "application")
    val application: GuildNotAuthorizedErrorDataApplication? = null,

    @Json(name = "discord")
    val discord: GuildNotAuthorizedErrorDataDiscord? = null

) {


}

