/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.NoPatronsFoundError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error 
 * @param status 
 */


data class NoPatronsFound (

    @Json(name = "error")
    val error: NoPatronsFoundError? = null,

    @Json(name = "status")
    val status: kotlin.String? = null

) {


}

